# Generated by Django 4.1 on 2022-10-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_location_shop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='ABCDE',
        ),
    ]
